### PR TITLE
Fix build warning on absolute docs link

### PR DESCRIPTION
**Pull request by dphansen**
Fix the build warning for docs.microsoft.com: 

> Absolute link 'https://docs.microsoft.com/dotnet/core/install/' will be broken in isolated environments. Replace with a relative link.

### CODE REVIEW

**Comment by bettinaheim** [comment]
> Hi @bettinaheim - would you be able to merge this PR? Thank you.

Sorry, I missed this ping. The link as edited won't work on this repo - and I am not sure it will work on the docs page either. Could you revise this?

**Review by bettinaheim — CHANGES_REQUESTED** [review]
Sorry, I missed this ping. The link as edited won't work on this repo - and I am not sure it will work on the docs page either. Could you revise this?

**Comment by dphansen** [comment]
@bettinaheim It will work on docs articles, as the build automatically adds `https://docs.microsoft.com/` in front of the link. Is it an issue that it doesn't work in the repo?

**Comment by Bradben** [comment]
@dphansen - This PR replaced by https://github.com/microsoft/qsharp-language/pull/127

**Pull request closed without merging**
