### PR TITLE
Fix typos in CallStatements.md

### PR DESCRIPTION
**Pull request by SoniaLopezBravo**
This closes [#331](https://github.com/MicrosoftDocs/quantum-docs/issues/331)

### CODE REVIEW

**Comment by SoniaLopezBravo** [comment]
Hi @bettinaheim, could you please review this?

**Comment by SoniaLopezBravo** [comment]
Hi @cgranade , could you please review this?

**Comment by SoniaLopezBravo** [comment]
Hi @cgranade, could you please review this?

**Review by alan-geller — APPROVED** [review]
Looks good to me.

**Pull request merged**
